version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/security-app
hooks:
  ApplicationStop: 
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - localtion: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user